name = "spotify-to-tg"
main = "main.js"
compatibility_date = "2024-09-23"

[vars]
SPOTIFY_CLIENT_ID = "a9611e578b8a44208fa30337b16e6701"

[[kv_namespaces]]
binding = "TOKENS"
id = "5707f3dfa09f4741a894f070dc278879"
preview_id = "1e9b1470dd6f4751af3e996a56599129"

[triggers]
crons = ["0/5 * * * * *"]  # Каждые 5 секунд

[env.production]
name = "spotify-to-tg-prod"

[env.production.vars]
SPOTIFY_CLIENT_ID = "a9611e578b8a44208fa30337b16e6701"

[[env.production.kv_namespaces]]
binding = "TOKENS"
id = "5707f3dfa09f4741a894f070dc278879"
